---
title: "Multiple comparisons"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)

```

## Our Dataset

### Using all p-values

The following uses all the p-values, even those that are repeated.

```{r}
# for OLS Data
olm <- OLM_coefficients_full <- readRDS("~/Dropbox/Eucs_phylo_traits/Output_figures/OLM_coefficients_full.rds")
olm$p_BH <- p.adjust(olm$P_value, "BH")
olm$p_Holm <- p.adjust(olm$P_value, "holm")
#write.csv(olm, file = "OLS_full_coefficients2.csv") # goes to where the multiple comparisons script is but can move it later

plot(olm$p_BH ~ olm$P_value, log = "xy", xlim = c(0.00001,0.1), ylim = c(0.00001,0.1))
abline(a=0, b=1, col = "gray60")
abline(v=0.05, col = "gray60")
abline(h=0.05, col = "gray60")
abline(v=0.0004, col = "gray60")
abline(h=0.0004, col = "gray60")
points(olm$p_Holm ~ olm$P_value, col = 2)

plot(olm$p_BH ~ olm$P_value,  xlim = c(0.00001,0.1), ylim = c(0.00001,0.1))
abline(a=0, b=1, col = "gray60")
points(olm$p_Holm ~ olm$P_value, col = 2)


# For PGLS Data
pgls <- readRDS("~/Dropbox/Eucs_phylo_traits/Input_data/PGLS_coefficients_full.RData")
pgls$p_BH <- p.adjust(pgls$P_value, "BH")
pgls$p_Holm <- p.adjust(pgls$P_value, "holm")
# write.csv(pgls, file = "PGLS_full_coefficients2.csv") # goes to where the multiple comparisons script is
```


### Only relevant p-values

The following use only a subset of the p-values

```{r}
# to load the full pgls P matrix unaltered (will need transposing and unlisting to turn into list)
pgls.P <- readRDS("~/Dropbox/Eucs_phylo_traits/Input_data/PGLS_P.rds")

# loads the log2 object from script 4 that allows the 
load("~/Dropbox/Eucs_phylo_traits/Input_data/halving_logical.RData")

pgls.P.half.2 <- matrix(NA, 11, 11) 
pgls.P.half.2[log2] <- as.matrix(pgls.P)[log2]
diag(pgls.P.half.2) <- c(rep(1111, 11))
pgls.P.list.full <- unlist(lapply(as.data.frame(t(pgls.P.half.2)),as.numeric))
class(pgls.P.list.full)
pgls.P.table <- data.frame('Labels' = c(1:length(pgls.P.list.full)), 'PGLS_half' = pgls.P.list.full)
# getting rid of the placeholder diagonal entries marked as 1111, this will then have the same pattern of missing data as where the p-values in the supplementary pgls full coefficients table has unbolded rows (I excluded the main diagonal entries before transfering them to the supps table anyway)
pgls.P.table <- pgls.P.table[!pgls.P.table$PGLS_half == 1111,]

# now for the pruned version that undergoes the multiple comparisons test
pgls.P.table.adj <- pgls.P.table[!is.na(pgls.P.table$PGLS_half),]
  ## checking if the data is being treated as numeric
class(pgls.P.table.adj$PGLS_half)
pgls.P.table.adj$PGLS_P_Holm <- p.adjust(pgls.P.table.adj$PGLS_half, "holm")
pgls.P.table.adj <- pgls.P.table.adj[c('Labels', 'PGLS_P_Holm')]
pgls.P.table <- left_join(pgls.P.table, pgls.P.table.adj)


# Now for the ols version
  ## remember the olm p matrix is already symmetrical
olm.P <- readRDS("~/Dropbox/Eucs_phylo_traits/Input_data/OLM_P.rds")

olm.P.half.2 <- matrix(NA, 11, 11) 
olm.P.half.2[log2] <- as.matrix(olm.P)[log2]
diag(olm.P.half.2) <- c(rep(1111, 11))
olm.P.list.full <- unlist(lapply(as.data.frame(t(olm.P.half.2)),as.numeric))
class(olm.P.list.full)
olm.P.table <- data.frame('Labels' = c(1:length(olm.P.list.full)), 'OLM_half' = olm.P.list.full)
# getting rid of the placeholder diagonal entries marked as 1111, this will then have the same pattern of missing data as where the p-values in the supplementary pgls full coefficients table has unbolded rows (I excluded the main diagonal entries before transfering them to the supps table anyway)
olm.P.table <- olm.P.table[!olm.P.table$OLM_half == 1111,]

# now for the pruned version that undergoes the multiple comparisons test
olm.P.table.adj <- olm.P.table[!is.na(olm.P.table$OLM_half),]
  ## checking if the data is being treated as numeric
class(olm.P.table.adj$OLM_half)
olm.P.table.adj$OLM_P_Holm <- p.adjust(olm.P.table.adj$OLM_half, "holm")
olm.P.table.adj <- olm.P.table.adj[c('Labels', 'OLM_P_Holm')]
olm.P.table <- left_join(olm.P.table, olm.P.table.adj)
olm.P.table.pruned <- olm.P.table[!is.na(olm.P.table$Labels),]
# now to left join to the PGLS one
P.table <- left_join(pgls.P.table, olm.P.table.pruned)
P.table[is.na(P.table)] <- "&*()"
write.csv(P.table, file = "../../Output_figures/Adjusted_P_values_for_supps.csv", row.names = FALSE)
```


